"""Generated-fixture review flow, first-run choice, persistence, selection and reflow."""
import os
import re
import sys
import time
import uuid
from pathlib import Path
from playwright.sync_api import sync_playwright, expect

base=sys.argv[1]
with sync_playwright() as p:
    browser=p.chromium.launch()
    page=browser.new_page(viewport={"width":1440,"height":1000})
    errors=[]
    page.on('pageerror',lambda e:errors.append(str(e)))
    request=p.request.new_context(base_url=base)
    def get(path):
        response=request.get('/api/v1/'+path)
        assert response.ok,response.text()
        return response.json()
    def job(mode, ids=None):
        response=request.post('/api/v1/jobs/start',data={'mode':mode,**({'file_ids':ids} if ids else {})})
        assert response.ok,response.text()
        ident=response.json()['id']
        for _ in range(240):
            result=get(f'runs/{ident}')
            if result['status'] not in ('Preparing','Running','Cancelling') and get('status')['active_job'] is None:
                assert result['status']=='Completed',result
                return
            time.sleep(.25)
        raise AssertionError('job did not settle')
    assert request.post('/api/v1/catalog').ok
    page.goto(base)
    page.get_by_role('button',name='Next',exact=True).click()
    choice=page.get_by_label('Small-image reminders (required)',exact=True)
    expect(choice).to_have_value('')
    expect(choice).to_have_attribute('required','')
    expect(page.get_by_text('Choose On or Off to continue.',exact=True)).to_be_visible()
    expect(page.locator('.settings-panel section').first).to_contain_text('Small-image review')
    if os.environ.get('SHOTS'): page.screenshot(path=os.environ['SHOTS']+'/review-first-run-required.png',full_page=True)
    page.get_by_role('button',name='Next',exact=True).click()
    expect(page.get_by_text('Choose whether to suggest small images for review.',exact=True)).to_be_visible()
    choice.select_option('on')
    page.get_by_label('Minimum shorter side (pixels)',exact=True).fill('800')
    page.get_by_role('button',name='Next',exact=True).click()
    page.get_by_role('button',name='Next',exact=True).click()
    page.get_by_role('button',name='Next',exact=True).click()
    page.get_by_role('button',name='Save and continue',exact=True).click()
    expect(page.get_by_role('button',name='Not organized',exact=False).first).to_have_attribute('aria-pressed','true')
    assert get('settings')['small_image_min']['value']==800
    job('index')
    page.reload()
    summary=page.get_by_role('region',name='Index summary')
    expect(summary).to_be_visible()
    expect(summary).to_contain_text('Similar photos compares organized photos in Library only.')
    expect(page.get_by_role('heading',name='Not organized',exact=True)).to_be_visible()
    size_help=summary.locator('.tip').filter(has_text='Image size unavailable')
    size_help.hover()
    expect(size_help.locator('.help-content')).to_contain_text('does not mean the file is damaged or is not a photo')
    size_help.locator('.help-trigger').focus()
    page.keyboard.press('Escape')
    summary.get_by_role('button',name='Close index summary',exact=True).click()
    expect(summary).to_have_count(0)
    show_summary=page.get_by_role('button',name='Show index summary',exact=True)
    expect(show_summary).to_be_focused()
    page.reload()
    expect(show_summary).to_be_visible()
    expect(summary).to_have_count(0)
    page.get_by_role('button',name='No capture date',exact=False).first.click()
    expect(summary).to_have_count(0)
    page.get_by_role('button',name='No capture date',exact=False).first.click()
    show_summary.click()
    expect(summary.get_by_role('button',name='Close index summary',exact=True)).to_be_focused()
    summary.get_by_role('button',name='Close index summary',exact=True).click()
    # A finished new Index resets dismissal without reloading the page.
    job('index')
    expect(summary).to_be_visible(timeout=15_000)
    page.locator('.card-image').first.click()
    expect(summary).to_have_count(0)
    expect(show_summary).to_be_visible()
    source_panel=page.locator('.inspector')
    expect(source_panel.get_by_role('tab',name='Similar photos',exact=True)).to_have_count(0)
    expect(source_panel.get_by_role('button',name='Review photo…',exact=True)).to_have_count(0)
    expect(source_panel.get_by_role('button',name='Review later…',exact=True)).to_have_count(0)
    expect(source_panel.get_by_role('button',name='Reject…',exact=True)).to_have_count(0)
    if os.environ.get('SHOTS'): page.screenshot(path=os.environ['SHOTS']+'/source-info-only.png')
    page.locator('.inspector').get_by_role('button',name='Close',exact=True).click()
    expect(summary).to_be_visible()
    assert get('photos?view=review')['total']==0
    assert get('photos?view=organized')['total']==0
    page.get_by_role('button',name='Copy all photos…',exact=True).click()
    expect(page.get_by_role('alertdialog')).to_be_visible()
    page.get_by_role('button',name='Cancel',exact=True).click()
    assert get('status')['active_job'] is None
    if os.environ.get('SHOTS'): page.screenshot(path=os.environ['SHOTS']+'/index-summary.png')
    page.set_viewport_size({'width':720,'height':500})
    assert page.evaluate('document.documentElement.scrollWidth <= innerWidth + 1')
    if os.environ.get('SHOTS'): page.screenshot(path=os.environ['SHOTS']+'/index-summary-reflow.png',full_page=True)
    page.set_viewport_size({'width':1440,'height':1000})
    job('copy')
    page.reload()
    # Explicit Not organized survives refresh, even though default is now Library.
    expect(page.get_by_role('button',name='Not organized',exact=False).first).to_have_attribute('aria-pressed','true')
    expect(summary).to_have_count(0)
    expect(show_summary).to_have_count(0)
    expect(page.get_by_role('button',name='Go to Library',exact=True)).to_be_visible()
    page.get_by_role('button',name='Go to Library',exact=True).click()
    page.goto(base)
    expect(page.get_by_role('button',name='Library (',exact=False).first).to_have_attribute('aria-pressed','true')
    cards=page.locator('.card')
    expect(cards.first).to_be_visible()
    first=int(cards.first.get_attribute('data-id'))
    cards.first.get_by_role('checkbox').check()
    page.get_by_label('Sort',exact=True).select_option('name')
    page.get_by_label('Search filenames',exact=True).fill('photo-')
    expect(page).to_have_url(__import__('re').compile(r'q=photo-'))
    expect(cards.first).to_be_visible()
    entry=cards.nth(20)
    entry.scroll_into_view_if_needed()
    opener=int(entry.get_attribute('data-id'))
    entry_y=entry.bounding_box()['y']
    if os.environ.get('SHOTS'): page.screenshot(path=os.environ['SHOTS']+'/library-review-markers.png',full_page=True)
    entry.get_by_role('link',name='Needs review',exact=False).click()
    review_dialog=page.get_by_role('dialog',name='Review photos',exact=True)
    expect(review_dialog).to_be_visible()
    expect(page).to_have_url(__import__('re').compile(fr'review_photo={opener}'))
    review_dialog.get_by_role('button',name='Back to gallery',exact=False).click()
    expect(page.get_by_role('group',name='Review reason').get_by_role('button',name='Small images',exact=False)).to_have_attribute('aria-pressed','true')
    page.get_by_role('button',name='Back to Library',exact=False).click()
    expect(page.get_by_label('Search filenames',exact=True)).to_have_value('photo-')
    expect(page.get_by_label('Sort',exact=True)).to_have_value('name')
    expect(page.locator(f'.card[data-id="{opener}"]')).to_be_visible()
    page.wait_for_function('(v) => Math.abs(document.querySelector(`.card[data-id="${v.id}"]`).getBoundingClientRect().y-v.y)<4',arg={'id':opener,'y':entry_y})
    expect(page.locator(f'.card[data-id="{first}"] input')).to_be_checked()
    page.get_by_label('Search filenames',exact=True).fill('')
    page.get_by_label('Sort',exact=True).select_option('newest')
    expect(page).not_to_have_url(__import__('re').compile(r'q='))
    size_filter=page.get_by_role('group',name='Filter photos',exact=True).get_by_role('button',name='Small images',exact=False)
    size_filter.click()
    expect(page.get_by_role('button',name='Library (',exact=False).first).to_have_attribute('aria-pressed','true')
    expect(size_filter).to_have_attribute('aria-pressed','true')
    size_filter.click()
    expect(size_filter).to_have_attribute('aria-pressed','false')
    page.locator('.card-image').first.click()
    inspector=page.locator('.inspector')
    expect(inspector.get_by_role('group',name='Photo actions')).to_be_visible()
    expect(inspector.get_by_role('button',name='Mark reviewed',exact=True)).to_have_count(0)
    expect(inspector.get_by_role('button',name='Change in Settings',exact=True)).to_have_count(0)
    expect(inspector.get_by_role('button',name='Review photo…',exact=True)).to_be_visible()
    page.get_by_role('button',name='Needs review (',exact=False).first.click()
    expect(inspector).to_have_count(0)
    expect(page.get_by_role('group',name='Filter photos',exact=True)).to_have_count(0)
    expect(page.get_by_role('group',name='Review reason')).to_be_visible()
    expect(page.get_by_role('button',name='Small images',exact=False)).to_have_count(1)
    page.get_by_role('group',name='Review reason').get_by_role('button',name='Small images',exact=False).click()
    expect(page.locator(f'.card[data-id="{first}"] input')).to_be_checked()
    # Switching reasons must not move the filter row or the results below it.
    reasons=page.get_by_role('group',name='Review reason',exact=True)
    for width,height in ((1440,1000),(720,500)):
        page.set_viewport_size({'width':width,'height':height})
        baseline=None
        for key,label in (('all','Small images'),('small','Small images'),('later','Review later'),('all','Review later'),('small','Small images')):
            with page.expect_response(lambda r: '/api/v1/photos?' in r.url and f'reason={key}' in r.url) as response:
                reasons.get_by_role('button',name=label,exact=False).click()
            total=response.value.json()['total']
            expect(page.locator('.gallery-summary').first).to_contain_text(f'{total} photo')
            positions=page.evaluate("[document.querySelector('[aria-label=\"Review reason\"]'),document.querySelector('.gallery-summary')].map(e=>e.getBoundingClientRect().top+scrollY)")
            if baseline is None: baseline=positions
            assert all(abs(a-b)<2 for a,b in zip(baseline,positions)),f'Reason {key} at {width}px moved layout: {baseline} -> {positions}'
            if os.environ.get('SHOTS') and key in ('all','small'):
                page.screenshot(path=os.environ['SHOTS']+f'/review-layout-{width}-{key}.png')
    page.set_viewport_size({'width':1440,'height':1000})
    card=page.locator(f'.card[data-id="{first}"]')
    expect(card.locator('.review-card-notes')).to_contain_text('Below minimum image size')
    expect(card.locator('.review-card-notes')).not_to_contain_text('320 × 240')
    card.locator('.review-card-notes .tip').hover()
    expect(card.locator('.help-content')).to_contain_text('800-pixel minimum on the shorter side')
    if os.environ.get('SHOTS'): page.screenshot(path=os.environ['SHOTS']+'/small-image-hover.png')
    card.locator('.review-card-notes .help-trigger').focus()
    page.keyboard.press('Escape')
    if os.environ.get('SHOTS'): page.screenshot(path=os.environ['SHOTS']+'/review-inbox.png',full_page=True)
    card.get_by_role('button',name='Review photo',exact=True).click()
    workspace=page.get_by_role('dialog',name='Review photos',exact=True)
    expect(workspace).to_be_visible()
    expect(workspace.get_by_role('region',name='Photo review',exact=True).get_by_text('Location: Library',exact=True)).to_be_visible()
    page.wait_for_function("[...document.querySelectorAll('.review-photo img')].some(i => i.complete && i.naturalWidth > 0)")
    if os.environ.get('SHOTS'): workspace.screenshot(path=os.environ['SHOTS']+'/review-workspace.png')
    expect(workspace.get_by_role('heading',name='Small-image review',exact=True)).to_be_visible()
    expect(workspace.get_by_role('group',name='Photo actions')).to_be_visible()
    page.emulate_media(color_scheme='dark')
    if os.environ.get('SHOTS'): workspace.screenshot(path=os.environ['SHOTS']+'/review-workspace-dark.png')
    page.emulate_media(color_scheme='light')
    expect(workspace.locator('.review-evidence img')).to_have_count(0)
    review_url=page.url
    review_position=workspace.locator('.workspace-step > span').inner_text()
    workspace.get_by_role('link',name=re.compile(r'^View all \d+ matches')).click()
    expect(workspace).to_have_count(0)
    matches=page.get_by_role('region',name='Matches for this photo',exact=True)
    expect(matches).to_be_visible()
    expect(page.locator(f'.card[data-id="{first}"] input')).to_be_checked()
    matches.get_by_role('button',name=re.compile('^Review side by side:')).first.click()
    comparison=page.get_by_role('dialog',name='Review photo match',exact=True)
    expect(comparison).to_be_visible()
    comparison.get_by_role('button',name='Back to gallery',exact=True).click()
    expect(comparison).to_have_count(0)
    page.go_back()
    expect(workspace).to_be_visible()
    expect(workspace.locator('.workspace-step > span')).to_have_text(review_position)
    assert page.url == review_url
    expect(page.locator(f'.card[data-id="{first}"] input')).to_be_checked()
    # Next is a skip, not a saved answer; Previous returns to the same photo.
    workspace.get_by_role('button',name='Next photo',exact=True).click()
    expect(workspace.locator('.workspace-step')).to_contain_text('Photo 2 of')
    assert [n['reason'] for n in get(f'photos/{first}/review')['reasons']]==['small']
    workspace.get_by_role('button',name='Previous photo',exact=True).click()
    expect(workspace.locator('.workspace-step')).to_contain_text('Photo 1 of')
    page.set_viewport_size({'width':720,'height':500})
    expect(workspace.get_by_role('button',name='Back to gallery',exact=False)).to_be_visible()
    assert workspace.evaluate('e => e.scrollWidth <= e.clientWidth + 1')
    if os.environ.get('SHOTS'): workspace.screenshot(path=os.environ['SHOTS']+'/review-workspace-reflow.png')
    page.set_viewport_size({'width':1440,'height':1000})
    workspace.get_by_role('button',name='Review later…',exact=True).click()
    workspace.get_by_label('Optional note',exact=True).fill('Only surviving small copy')
    workspace.get_by_role('button',name='Save reminder',exact=True).click()
    expect(workspace.get_by_text('Added to Review later.',exact=True)).to_be_visible()
    # A refused save cannot dismiss the reminder; retry retains the same decision.
    page.route(f'**/api/v1/photos/{first}/review', lambda route: route.fulfill(status=503,json={'error':{'code':'review_unavailable','message':'Generated refusal'}}) if route.request.method=='POST' else route.continue_())
    workspace.get_by_role('button',name='Mark reviewed',exact=True).click()
    expect(workspace.get_by_role('button',name='Retry saving',exact=True)).to_be_visible()
    assert 'small' in [n['reason'] for n in get(f'photos/{first}/review')['reasons']]
    page.unroute(f'**/api/v1/photos/{first}/review')
    workspace.get_by_role('button',name='Retry saving',exact=True).click()
    expect(workspace.get_by_text('Size reviewed. The photo stays in your library.',exact=True)).to_be_visible()
    expect(workspace.get_by_role('button',name='Mark reviewed',exact=True)).to_be_enabled()
    workspace.get_by_role('button',name='Back to gallery',exact=False).click()
    detail=get(f'photos/{first}/review')
    assert [n['reason'] for n in detail['reasons']]==['later'],detail
    page.get_by_role('button',name='Review later (',exact=False).first.click()
    expect(page.locator(f'.card[data-id="{first}"]')).to_be_visible()
    page.reload()
    expect(page.locator(f'.card[data-id="{first}"]')).to_be_visible()
    # Leaving the inbox cannot carry a hidden Review later restriction into Library.
    page.get_by_role('button',name='Library (',exact=False).first.click()
    expect(page).not_to_have_url(__import__('re').compile(r'reason=later'))
    expect(page.locator('.card')).to_have_count(60)
    page.get_by_role('button',name='Needs review (',exact=False).first.click()
    page.get_by_role('button',name='Review later (',exact=False).first.click()
    page.locator(f'.card[data-id="{first}"] .card-image').click()
    expect(inspector).to_be_visible()
    inspector.get_by_role('button',name='Review photo…',exact=True).click()
    workspace.get_by_role('button',name='Done',exact=True).click()
    expect(workspace).to_have_count(0)
    expect(inspector).to_have_count(0)
    expect(page.get_by_role('status').filter(has_text='Review later reminder cleared. No photos remain in this review.')).to_be_visible()
    expect(page.locator('.gallery-summary').first).to_contain_text('0 photos')
    expect(page.get_by_role('button',name='Review later (',exact=False).first).to_have_attribute('aria-pressed','true')
    assert 'photo=' not in page.url and 'review_photo=' not in page.url
    for width in (1440,720):
        page.set_viewport_size({'width':width,'height':1000})
        expect(page.get_by_role('status').filter(has_text='No photos remain in this review.')).to_be_visible()
        assert page.evaluate('document.documentElement.scrollWidth <= innerWidth + 1')
        if os.environ.get('SHOTS'): page.screenshot(path=os.environ['SHOTS']+f'/review-queue-complete-{width}.png')
    page.set_viewport_size({'width':1440,'height':1000})
    assert not get(f'photos/{first}/review')['reasons']
    job('index')
    assert not get(f'photos/{first}/review')['reasons'],'Index resurrected review'
    # With a nonempty queue, Back keeps only previews that still match its filters.
    another=next(i['id'] for i in get('photos?view=organized&page_size=60')['items'] if i['id'] != first)
    for ident in (first,another):
        detail=get(f'photos/{ident}/review')
        saved=request.post(f'/api/v1/photos/{ident}/review',data={
            'photo_id':ident,'sha1':detail['sha1'],'revision':detail['revision'],
            'reason':'later','action':'later','note':'Generated queue regression','request_id':uuid.uuid4().hex})
        assert saved.ok,saved.text()
    queued=get('photos?view=review&reason=later')['items']
    reviewed,remaining=queued[0]['id'],queued[1]['id']
    page.goto(base+f'/?view=review&reason=later&photo={reviewed}')
    expect(inspector).to_be_visible()
    inspector.get_by_role('button',name='Review photo…',exact=True).click()
    expect(workspace.locator('.workspace-step')).to_contain_text('Photo 1 of 2')
    workspace.get_by_role('button',name='Back to gallery',exact=True).click()
    expect(inspector).to_be_visible()
    assert f'photo={reviewed}' in page.url
    inspector.get_by_role('button',name='Review photo…',exact=True).click()
    workspace.get_by_role('button',name='Done',exact=True).click()
    expect(workspace.locator('.workspace-step')).to_contain_text('Photo 1 of 1')
    expect(page).to_have_url(re.compile(fr'review_photo={remaining}(?:&|$)'))
    workspace.get_by_role('button',name='Back to gallery',exact=True).click()
    expect(inspector).to_have_count(0)
    expect(page.locator('.gallery-summary').first).to_contain_text('1 photo')
    page.locator(f'.card[data-id="{remaining}"] .card-image').click()
    inspector.get_by_role('button',name='Review photo…',exact=True).click()
    workspace.get_by_role('button',name='Done',exact=True).click()
    expect(workspace).to_have_count(0)
    expect(inspector).to_have_count(0)
    # Reject is the existing confirmed engine workflow, not a catalog-only dismissal.
    page.goto(base+'/?view=review&reason=small')
    expect(page.locator('.card').first).to_be_visible()
    rejected=int(page.locator('.card').first.get_attribute('data-id'))
    page.locator('.card').first.get_by_role('button',name='Review photo',exact=True).click()
    workspace.get_by_role('button',name='Reject…',exact=True).click()
    page.get_by_role('alertdialog').get_by_role('button',name='Reject',exact=True).click()
    expect(workspace.get_by_text('Photo moved to Rejects.',exact=True)).to_be_visible(timeout=60000)
    assert get(f'photos/{rejected}/inspect')['status']=='Rejected_Copied'
    assert not get(f'photos/{rejected}/review')['reasons']
    workspace.get_by_role('button',name='Back to gallery',exact=False).click()
    page.goto(base+'/?view=organized&suspicious=1&undated=1')
    page.get_by_role('button',name='Clear filters',exact=True).click()
    expect(page.get_by_role('button',name='Library (',exact=False).first).to_have_attribute('aria-pressed','true')
    page.get_by_role('button',name='Needs review (',exact=False).first.click()
    small=page.get_by_role('button',name='Small images (',exact=False).first
    if small.get_attribute('aria-pressed') != 'true': small.click()
    page.get_by_role('button',name='Change in Settings',exact=True).click()
    dialog=page.get_by_role('dialog',name='Settings',exact=True)
    expect(dialog.get_by_role('tab',name='Files',exact=True)).to_have_attribute('aria-selected','true')
    dialog.get_by_label('Small-image reminders',exact=True).select_option('off')
    dialog.get_by_role('button',name='Save settings',exact=True).click()
    expect(dialog.get_by_text('Saved.',exact=True)).to_be_visible()
    dialog.get_by_role('button',name='Close settings',exact=True).click()
    expect(page.get_by_role('button',name='Small images (0)',exact=True)).to_be_visible()
    page.goto(base+'/?view=organized')
    page.get_by_role('button',name='Has similar photos',exact=False).first.click()
    page.get_by_role('button',name='No capture date',exact=False).first.click()
    expect(page.get_by_role('button',name='Has similar photos',exact=False).first).to_have_attribute('aria-pressed','true')
    expect(page.get_by_role('button',name='No capture date',exact=False).first).to_have_attribute('aria-pressed','true')
    if os.environ.get('SHOTS'):
        page.screenshot(path=os.environ['SHOTS']+'/review-desktop.png',full_page=True)
    page.set_viewport_size({'width':720,'height':500})
    expect(page.get_by_role('button',name='Needs review',exact=False).first).to_be_visible()
    if os.environ.get('SHOTS'):
        page.screenshot(path=os.environ['SHOTS']+'/review-reflow.png',full_page=True)
    # A generated response models the final failed-only source view.
    def failures_only(route):
        response=route.fetch()
        payload=response.json()
        if payload.get('index_summary') is not None:
            payload['index_summary'].update(photos=3,ready=0,unfinished=0,failed=3)
        route.fulfill(response=response,json=payload)
    page.route('**/api/v1/photos?*',failures_only)
    page.evaluate("localStorage.removeItem('ns.closedIndexSummary')")
    page.goto(base+'/?view=unorganized')
    summary=page.get_by_role('region',name='Index summary')
    expect(summary.get_by_role('heading',name='3 files need attention',exact=True)).to_be_visible()
    expect(summary.get_by_role('link',name='View failures',exact=True)).to_have_attribute('href','/logs?status=Failed')
    expect(summary.get_by_role('button',name='Copy all photos…',exact=True)).to_have_count(0)
    expect(summary).not_to_contain_text('Copy or move them to build your library.')
    page.unroute('**/api/v1/photos?*',failures_only)
    candidates=get('photos?view=organized&similar=1&page_size=1')['items']
    assert candidates, 'Generated catalog must contain matching Library photos'
    chosen=candidates[0]['id']
    page.goto(base+f'/?view=organized&photo={chosen}&review_photo={chosen}&match_min=90')
    expect(page.locator('.review-evidence')).to_be_visible()
    before=get(f'similar/{chosen}?threshold=90')['total']
    assert before > 3, 'Fixture must demonstrate the full match count'
    expect(page.locator('.review-evidence img')).to_have_count(0)
    page.get_by_role('link',name=f'View all {before} matches →',exact=True).click()
    expect(page.get_by_role('dialog',name='Review photos',exact=True)).to_have_count(0)
    expect(page.get_by_role('tab',name='Similar photos',exact=True)).to_have_attribute('aria-selected','true')
    expect(page.get_by_role('region',name='Matches for this photo',exact=True)).to_be_visible()
    assert f'photo={chosen}' in page.url and 'match=90' in page.url
    page.go_back()
    expect(workspace).to_be_visible()
    assert f'review_photo={chosen}' in page.url
    print('Match-count link reuses similarity and browser Back restores review, filters and selection')
    assert not errors,errors
    print('PASS: first-run choice, place default, review persistence, independent reasons, selection, re-index, chips and Settings route')
    browser.close()
